name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@5e716dcfd653738c2d1db099bfba194a84158be4 # v2.3.0
      - name: Docker login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERIO_TOKEN }}
      - name: Docker build
        run: make release
      - name: Docker build latest
        run: VERSION=latest make release
      - name: Docker build versioned
        run: VERSION=${{ github.ref_name }} make release
